version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/DJANGO-POSTGRES-DOCKER-STARTER

    steps:
      # Step 1: obtain repo from github
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source .env/bin/activate
            flake8 --exclude=.env* --statistics
            pytest -v --cov=calculator

